service: line2chatgpt
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  timeout: 70
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "*"
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1

custom:
  pythonRequirements:
    usePipenv: true
  defaultStage: dev
  environment:
    prod: ${file(./env/prod.yml)}
    dev: ${file(./env/dev.yml)}
functions:
  hello:
    handler: handler.webhook
    environment: ${self:custom.environment.${self:provider.stage}}
    url: true

# DynamoDB
resources:
  Resources:
    MessageHistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.environment.${self:provider.stage}.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-python-requirements